"""Initial schema.

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-10-01

Written as plain SQL so every constraint is explicit and reviewable. The key one is
``ex_bookings_no_overlap``: PostgreSQL itself refuses two active bookings whose time
ranges overlap on the same turf, so double-booking is impossible even when two
requests race each other.
"""

from alembic import op

revision = "0001_initial_schema"
down_revision = None
branch_labels = None
depends_on = None

UPGRADE_SQL = """
CREATE EXTENSION IF NOT EXISTS btree_gist;

CREATE TABLE users (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name             VARCHAR(50)  NOT NULL,
    last_name              VARCHAR(50)  NOT NULL,
    email                  VARCHAR(255) NOT NULL,
    phone                  VARCHAR(15)  NOT NULL,
    password_hash          VARCHAR(255) NOT NULL,
    role                   VARCHAR(20)  NOT NULL DEFAULT 'user',
    is_active              BOOLEAN      NOT NULL DEFAULT TRUE,
    profile_image_url      VARCHAR(500),
    profile_image_key      VARCHAR(300),
    token_version          INTEGER      NOT NULL DEFAULT 0,
    reset_code_hash        VARCHAR(128),
    reset_code_expires_at  TIMESTAMPTZ,
    reset_attempts         INTEGER      NOT NULL DEFAULT 0,
    accepted_terms_at      TIMESTAMPTZ,
    created_at             TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at             TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT uq_users_phone UNIQUE (phone),
    CONSTRAINT ck_users_role CHECK (role IN ('user', 'owner', 'admin')),
    CONSTRAINT ck_users_email_lowercase CHECK (email = lower(email))
);

CREATE TABLE amenities (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR(50) NOT NULL,
    CONSTRAINT uq_amenities_name UNIQUE (name)
);

CREATE TABLE turfs (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id           BIGINT        NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
    name               VARCHAR(200)  NOT NULL,
    slug               VARCHAR(220)  NOT NULL,
    sport_type         VARCHAR(20)   NOT NULL,
    description        TEXT          NOT NULL DEFAULT '',
    location           VARCHAR(255)  NOT NULL,
    address            VARCHAR(255)  NOT NULL,
    latitude           NUMERIC(9, 6),
    longitude          NUMERIC(9, 6),
    length_m           INTEGER       NOT NULL,
    width_m            INTEGER       NOT NULL,
    surface_type       VARCHAR(20)   NOT NULL,
    capacity           INTEGER       NOT NULL,
    price_per_hour     NUMERIC(10, 2) NOT NULL,
    min_booking_hours  SMALLINT      NOT NULL DEFAULT 1,
    max_booking_hours  SMALLINT      NOT NULL DEFAULT 4,
    opening_time       TIME          NOT NULL,
    closing_time       TIME          NOT NULL,
    status             VARCHAR(20)   NOT NULL DEFAULT 'open',
    is_verified        BOOLEAN       NOT NULL DEFAULT FALSE,
    is_active          BOOLEAN       NOT NULL DEFAULT TRUE,
    cover_image_url    VARCHAR(500),
    cover_image_key    VARCHAR(300),
    rating_avg         NUMERIC(3, 2) NOT NULL DEFAULT 0,
    review_count       INTEGER       NOT NULL DEFAULT 0,
    created_at         TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT uq_turfs_slug UNIQUE (slug),
    CONSTRAINT ck_turfs_sport_type CHECK (sport_type IN ('football', 'cricket', 'tennis', 'badminton', 'multi')),
    CONSTRAINT ck_turfs_surface_type CHECK (surface_type IN ('natural', 'artificial', 'clay', 'hard', 'synthetic')),
    CONSTRAINT ck_turfs_status CHECK (status IN ('open', 'closed', 'maintenance')),
    CONSTRAINT ck_turfs_price_positive CHECK (price_per_hour > 0),
    CONSTRAINT ck_turfs_dimensions_positive CHECK (length_m > 0 AND width_m > 0 AND capacity > 0),
    CONSTRAINT ck_turfs_booking_hours CHECK (min_booking_hours >= 1 AND max_booking_hours >= min_booking_hours),
    CONSTRAINT ck_turfs_coordinates CHECK (
        (latitude IS NULL AND longitude IS NULL)
        OR (latitude BETWEEN -90 AND 90 AND longitude BETWEEN -180 AND 180)
    ),
    CONSTRAINT ck_turfs_rating CHECK (rating_avg BETWEEN 0 AND 5)
);
CREATE INDEX ix_turfs_owner_id ON turfs (owner_id);
CREATE INDEX ix_turfs_search ON turfs (is_active, is_verified, sport_type, price_per_hour);
CREATE INDEX ix_turfs_coordinates ON turfs (latitude, longitude) WHERE latitude IS NOT NULL;

CREATE TABLE turf_amenities (
    turf_id     BIGINT NOT NULL REFERENCES turfs (id) ON DELETE CASCADE,
    amenity_id  BIGINT NOT NULL REFERENCES amenities (id) ON DELETE CASCADE,
    PRIMARY KEY (turf_id, amenity_id)
);
CREATE INDEX ix_turf_amenities_amenity_id ON turf_amenities (amenity_id);

CREATE TABLE turf_images (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    turf_id      BIGINT       NOT NULL REFERENCES turfs (id) ON DELETE CASCADE,
    url          VARCHAR(500) NOT NULL,
    storage_key  VARCHAR(300) NOT NULL,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX ix_turf_images_turf_id ON turf_images (turf_id);

CREATE TABLE bookings (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference                VARCHAR(16)    NOT NULL,
    turf_id                  BIGINT         NOT NULL REFERENCES turfs (id) ON DELETE RESTRICT,
    user_id                  BIGINT         NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
    start_at                 TIMESTAMPTZ    NOT NULL,
    end_at                   TIMESTAMPTZ    NOT NULL,
    status                   VARCHAR(20)    NOT NULL DEFAULT 'pending',
    total_amount             NUMERIC(10, 2) NOT NULL,
    notes                    TEXT           NOT NULL DEFAULT '',
    payment_status           VARCHAR(20)    NOT NULL DEFAULT 'unpaid',
    payment_method           VARCHAR(20),
    payment_reference        VARCHAR(100),
    paid_amount              NUMERIC(10, 2),
    paid_at                  TIMESTAMPTZ,
    payment_confirmed_by_id  BIGINT REFERENCES users (id) ON DELETE SET NULL,
    hold_expires_at          TIMESTAMPTZ,
    cancelled_at             TIMESTAMPTZ,
    cancelled_by_id          BIGINT REFERENCES users (id) ON DELETE SET NULL,
    cancellation_reason      VARCHAR(255),
    created_at               TIMESTAMPTZ    NOT NULL DEFAULT now(),
    updated_at               TIMESTAMPTZ    NOT NULL DEFAULT now(),
    CONSTRAINT uq_bookings_reference UNIQUE (reference),
    CONSTRAINT ck_bookings_time_range CHECK (end_at > start_at),
    CONSTRAINT ck_bookings_amount CHECK (total_amount >= 0 AND (paid_amount IS NULL OR paid_amount >= 0)),
    CONSTRAINT ck_bookings_status CHECK (status IN ('pending', 'confirmed', 'cancelled', 'completed', 'expired')),
    CONSTRAINT ck_bookings_payment_status CHECK (payment_status IN ('unpaid', 'paid', 'refund_pending', 'refunded')),
    CONSTRAINT ck_bookings_payment_method CHECK (
        payment_method IS NULL OR payment_method IN ('cash', 'upi', 'bank_transfer', 'card')
    ),
    -- A booking can only be confirmed once it has been paid.
    CONSTRAINT ck_bookings_confirmed_is_paid CHECK (
        status NOT IN ('confirmed', 'completed') OR payment_status = 'paid'
    ),
    -- No two active bookings may overlap on the same turf. '[)' makes back-to-back slots legal.
    CONSTRAINT ex_bookings_no_overlap EXCLUDE USING gist (
        turf_id WITH =,
        tstzrange(start_at, end_at, '[)') WITH &&
    ) WHERE (status IN ('pending', 'confirmed'))
);
CREATE INDEX ix_bookings_user_start ON bookings (user_id, start_at DESC);
CREATE INDEX ix_bookings_turf_start ON bookings (turf_id, start_at);
CREATE INDEX ix_bookings_pending_holds ON bookings (hold_expires_at) WHERE status = 'pending';

CREATE TABLE reviews (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    turf_id     BIGINT      NOT NULL REFERENCES turfs (id) ON DELETE CASCADE,
    user_id     BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    rating      SMALLINT    NOT NULL,
    comment     TEXT        NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_reviews_turf_user UNIQUE (turf_id, user_id),
    CONSTRAINT ck_reviews_rating CHECK (rating BETWEEN 1 AND 5)
);
CREATE INDEX ix_reviews_turf_id ON reviews (turf_id, created_at DESC);

CREATE TABLE favourites (
    user_id     BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    turf_id     BIGINT      NOT NULL REFERENCES turfs (id) ON DELETE CASCADE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, turf_id)
);

CREATE TABLE notifications (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    title       VARCHAR(120) NOT NULL,
    message     TEXT         NOT NULL,
    type        VARCHAR(20)  NOT NULL DEFAULT 'info',
    turf_id     BIGINT REFERENCES turfs (id) ON DELETE SET NULL,
    booking_id  BIGINT REFERENCES bookings (id) ON DELETE SET NULL,
    is_read     BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_notifications_type CHECK (type IN ('info', 'offer', 'alert', 'booking'))
);
CREATE INDEX ix_notifications_user ON notifications (user_id, is_read, created_at DESC);
"""

DOWNGRADE_SQL = """
DROP TABLE IF EXISTS notifications;
DROP TABLE IF EXISTS favourites;
DROP TABLE IF EXISTS reviews;
DROP TABLE IF EXISTS bookings;
DROP TABLE IF EXISTS turf_images;
DROP TABLE IF EXISTS turf_amenities;
DROP TABLE IF EXISTS turfs;
DROP TABLE IF EXISTS amenities;
DROP TABLE IF EXISTS users;
"""


def _run(sql: str) -> None:
    # One statement per execute() call: drivers using the extended query protocol
    # (like psycopg 3) reject several statements in a single call.
    for statement in sql.split(";\n"):
        if statement.strip():
            op.execute(statement)


def upgrade() -> None:
    _run(UPGRADE_SQL)


def downgrade() -> None:
    _run(DOWNGRADE_SQL)
